site_name: PyElli Documentation
site_description: |
  The documentation of pyElli
repo_url: https://github.com/PyEllips/pyElli
edit_uri: ""
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.code.copy
  palette:
    primary: cyan
    accent: teal

nav:
  - Getting Started:
    - index.md
    - contributing.md
  - Tutorials:
    - tutorial/index.md
    - tutorial/simple_fit.md
    - tutorial/working_with_dispersions.md
  - How-Tos:
    - howto/index.md
    - howto/fitting_multiple_angles.md
    - howto/mueller_matrix.md
  - Learning:
    - explanation/index.md
    - explanation/data_structure.md
    - explanation/class_structure.md
    - explanation/formula_dispersions.md
  - Reference:
    - reference/index.md
    - reference/solvers.md
    - reference/kkr.md
    - reference/changelog.md

plugins:
  - search
  - plotly
  - api-autonav:
      modules: ['src/elli']
      nav_section_title: "Reference"
  - mkdocstrings:
      default_handler: python
      locale: en
      handlers:
        python:
          options:
            show_root_heading: false
            show_source: false

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

extra_javascript:
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js